/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-10 16:50:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class addPatient_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("  <title>Patient Data App</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/defaultHeader.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("  <h2>Add New Patient</h2>\n");
      out.write("  <form method=\"POST\" action=\"/add\">\n");
      out.write("    <label>ID *</label>\n");
      out.write("    <input type=\"text\" name=\"ID\" placeholder=\"ID\" required/><br/>\n");
      out.write("    <label>BIRTHDATE *</label>\n");
      out.write("    <input type=\"text\" name=\"BIRTHDATE\" placeholder=\"YYYY-MM-DD\" required/><br/>\n");
      out.write("    <label>DEATHDATE</label>\n");
      out.write("    <input type=\"text\" name=\"DEATHDATE\" placeholder=\"YYYY-MM-DD\"/><br/>\n");
      out.write("    <label>SSN</label>\n");
      out.write("    <input type=\"text\" name=\"SSN\" placeholder=\"SSN\"/><br/>\n");
      out.write("    <label>DRIVERS</label>\n");
      out.write("    <input type=\"text\" name=\"DRIVERS\" placeholder=\"DRIVERS\"/><br/>\n");
      out.write("    <label>PASSPORT</label>\n");
      out.write("    <input type=\"text\" name=\"PASSPORT\" placeholder=\"PASSPORT\"/><br/>\n");
      out.write("    <label>PREFIX</label>\n");
      out.write("    <input type=\"text\" name=\"PREFIX\" placeholder=\"PREFIX\"/><br/>\n");
      out.write("    <label>FIRST *</label>\n");
      out.write("    <input type=\"text\" name=\"FIRST\" placeholder=\"FIRST\" required/><br/>\n");
      out.write("    <label>LAST *</label>\n");
      out.write("    <input type=\"text\" name=\"LAST\" placeholder=\"LAST\" required/><br/>\n");
      out.write("    <label>SUFFIX</label>\n");
      out.write("    <input type=\"text\" name=\"SUFFIX\" placeholder=\"SUFFIX\"/><br/>\n");
      out.write("    <label>MAIDEN</label>\n");
      out.write("    <input type=\"text\" name=\"MAIDEN\" placeholder=\"MAIDEN\"/><br/>\n");
      out.write("    <label>MARITAL</label>\n");
      out.write("    <input type=\"text\" name=\"MARITAL\" placeholder=\"MARITAL\"/><br/>\n");
      out.write("    <label>RACE</label>\n");
      out.write("    <input type=\"text\" name=\"RACE\" placeholder=\"RACE\"/><br/>\n");
      out.write("    <label>ETHNICITY</label>\n");
      out.write("    <input type=\"text\" name=\"ETHNICITY\" placeholder=\"ETHNICITY\"/><br/>\n");
      out.write("    <label>GENDER *</label>\n");
      out.write("    <input type=\"text\" name=\"GENDER\" placeholder=\"M or F\" required/><br/>\n");
      out.write("    <label>BIRTHPLACE</label>\n");
      out.write("    <input type=\"text\" name=\"BIRTHPLACE\" placeholder=\"BIRTHPLACE\"/><br/>\n");
      out.write("    <label>ADDRESS</label>\n");
      out.write("    <input type=\"text\" name=\"ADDRESS\" placeholder=\"ADDRESS\"/><br/>\n");
      out.write("    <label>CITY</label>\n");
      out.write("    <input type=\"text\" name=\"CITY\" placeholder=\"CITY\"/><br/>\n");
      out.write("    <label>STATE</label>\n");
      out.write("    <input type=\"text\" name=\"STATE\" placeholder=\"STATE\"/><br/>\n");
      out.write("    <label>ZIP</label>\n");
      out.write("    <input type=\"text\" name=\"ZIP\" placeholder=\"ZIP\"/><br/>\n");
      out.write("    <button type=\"submit\">Submit</button>\n");
      out.write("  </form>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
