/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-14 15:42:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.List;
import java.util.ArrayList;
import java.util.HashMap;

public final class patientList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("  <title>Patient Data App</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/patientListHeader.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("  <h2>Patients:</h2>\n");
      out.write("  ");

    String errorMessage = (String) request.getAttribute("errorMessage");
    if (errorMessage != null)
    {
  
      out.write("\n");
      out.write("      <p class=\"error-message\">");
      out.print( errorMessage );
      out.write("</p>\n");
      out.write("  ");

    }
  
      out.write("\n");
      out.write("\n");
      out.write("  ");

    String[] columnNames = (String[]) request.getAttribute("columnNames");
    ArrayList<ArrayList<String>> data = (ArrayList<ArrayList<String>>) request.getAttribute("patientData");
    int currentPage = (Integer) request.getAttribute("currentPage");
    int totalPages = (Integer) request.getAttribute("totalPages");
    int totalPatients = (Integer) request.getAttribute("totalPatients");
  
      out.write("\n");
      out.write("\n");
      out.write("  <p>Showing page ");
      out.print( currentPage );
      out.write(" of ");
      out.print( totalPages );
      out.write(' ');
      out.write('(');
      out.print( totalPatients );
      out.write(" patients total)</p>\n");
      out.write("\n");
      out.write("  <div class=\"pagination\">\n");
      out.write("    ");
 if (currentPage > 1) { 
      out.write("\n");
      out.write("      <a href=\"/patientList?page=1\">First</a>\n");
      out.write("      <a href=\"/patientList?page=");
      out.print( currentPage - 1 );
      out.write("\">Previous</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");

      int startPage = Math.max(1, currentPage - 2);
      int endPage = Math.min(totalPages, currentPage + 2);
      for (int p = startPage; p <= endPage; p++) {
    
      out.write("\n");
      out.write("      ");
 if (p == currentPage) { 
      out.write("\n");
      out.write("        <strong>");
      out.print( p );
      out.write("</strong>\n");
      out.write("      ");
 } else { 
      out.write("\n");
      out.write("        <a href=\"/patientList?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (currentPage < totalPages) { 
      out.write("\n");
      out.write("      <a href=\"/patientList?page=");
      out.print( currentPage + 1 );
      out.write("\">Next</a>\n");
      out.write("      <a href=\"/patientList?page=");
      out.print( totalPages );
      out.write("\">Last</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("  <table>\n");
      out.write("    <tr>\n");
      out.write("      ");
 if (columnNames != null) { for (String col : columnNames) { 
      out.write("\n");
      out.write("        <th>");
      out.print( col );
      out.write("</th>\n");
      out.write("      ");
 } } 
      out.write("\n");
      out.write("      <th></th>\n");
      out.write("    </tr>\n");
      out.write("    ");
 if (data != null && data.size() > 0) {
         for (int i = 0; i < data.size(); i++) { 
      out.write("\n");
      out.write("      <tr onclick=\"window.location='/patient?id=");
      out.print( data.get(i).get(0) );
      out.write("'\">\n");
      out.write("        ");
 for (int j = 0; j < data.get(i).size(); j++) { 
      out.write("\n");
      out.write("          <td><a href=\"/patient?id=");
      out.print( data.get(i).get(0) );
      out.write('"');
      out.write('>');
      out.print( data.get(i).get(j) );
      out.write("</a></td>\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("          <td>\n");
      out.write("            <form action=\"/delete\" method=\"post\">\n");
      out.write("              <input type=\"hidden\" name=\"patientId\" value=\"");
      out.print( data.get(i).get(0) );
      out.write("\">\n");
      out.write("              <button type=\"submit\" onclick=\"event.stopPropagation()\">Delete</button>\n");
      out.write("            </form>\n");
      out.write("          </td>\n");
      out.write("      </tr>\n");
      out.write("    ");
 } } 
      out.write("\n");
      out.write("  </table>\n");
      out.write("\n");
      out.write("  <div class=\"pagination\">\n");
      out.write("    ");
 if (currentPage > 1) { 
      out.write("\n");
      out.write("      <a href=\"/patientList?page=1\">First</a>\n");
      out.write("      <a href=\"/patientList?page=");
      out.print( currentPage - 1 );
      out.write("\">Previous</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");

      for (int p = startPage; p <= endPage; p++) {
    
      out.write("\n");
      out.write("      ");
 if (p == currentPage) { 
      out.write("\n");
      out.write("        <strong>");
      out.print( p );
      out.write("</strong>\n");
      out.write("      ");
 } else { 
      out.write("\n");
      out.write("        <a href=\"/patientList?page=");
      out.print( p );
      out.write('"');
      out.write('>');
      out.print( p );
      out.write("</a>\n");
      out.write("      ");
 } 
      out.write("\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("\n");
      out.write("    ");
 if (currentPage < totalPages) { 
      out.write("\n");
      out.write("      <a href=\"/patientList?page=");
      out.print( currentPage + 1 );
      out.write("\">Next</a>\n");
      out.write("      <a href=\"/patientList?page=");
      out.print( totalPages );
      out.write("\">Last</a>\n");
      out.write("    ");
 } 
      out.write("\n");
      out.write("  </div>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
