/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.4
 * Generated at: 2026-03-14 16:31:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;

public final class statistics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(4);
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/chart.js\"></script>\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/meta.jsp", out, false);
      out.write("\n");
      out.write("  <title>Patient Data App</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/defaultHeader.jsp", out, false);
      out.write("\n");
      out.write("<div class=\"main\">\n");
      out.write("  <h1>Statistics</h1>\n");
      out.write("\n");
      out.write(" ");

  Integer oldestAge = (Integer) request.getAttribute("oldestPerson");
  Integer youngestAge = (Integer) request.getAttribute("youngestPerson");
  Integer averageAge = (Integer) request.getAttribute("averageAge");
  Integer alive = (Integer) request.getAttribute("alive");
  Integer dead = (Integer) request.getAttribute("dead");
  Integer male = (Integer) request.getAttribute("male");
  Integer female = (Integer) request.getAttribute("female");
  Integer married = (Integer) request.getAttribute("married");
  Integer single = (Integer) request.getAttribute("single");
  Integer unknown = (Integer) request.getAttribute("unknown");
  Integer total = (Integer) request.getAttribute("total");
  

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"stats-wrapper\">\n");
      out.write("    <div class=\"stats-card\">\n");
      out.write("        <h2>Key Facts</h2>\n");
      out.write("        <ul>\n");
      out.write("            <li>Age of Oldest Patient: ");
      out.print( oldestAge );
      out.write("</li>\n");
      out.write("            <li>Age of Youngest Patient: ");
      out.print( youngestAge );
      out.write("</li>\n");
      out.write("            <li>Average Age: ");
      out.print( averageAge );
      out.write("</li>\n");
      out.write("            <li>Total Patients: ");
      out.print( total );
      out.write("</li>\n");
      out.write("        </ul>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<div class=\"charts-row\">\n");
      out.write("    <div style=\"chart-box\">\n");
      out.write("        <h3>Alive vs Dead</h3>\n");
      out.write("        <canvas id=\"aliveDeadChart\"></canvas>\n");
      out.write("    </div>\n");
      out.write("    <div style=\"chart-box\">\n");
      out.write("        <h3>Male vs Female</h3>\n");
      out.write("        <canvas id=\"maleFemaleChart\"></canvas>\n");
      out.write("    </div>\n");
      out.write("    <div style=\"chart-box\">\n");
      out.write("        <h3>Marital Status</h3>\n");
      out.write("        <canvas id=\"marriedSingleChart\"></canvas>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"charts-row-wide\">\n");
      out.write("    <div class=\"chart-box-wide\">\n");
      out.write("        <h3>Age Ranges</h3>\n");
      out.write("        <canvas id=\"ageChart\"></canvas>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"chart-box-wide\">\n");
      out.write("        <h3>Ethnicities</h3>\n");
      out.write("        <canvas id=\"ethnicityChart\"></canvas>\n");
      out.write("    </div>\n");
      out.write("</div>\n");
      out.write("\n");

    Map<String, Integer> ageData = (Map<String, Integer>) request.getAttribute("ageData");
    Map<String, Integer> ethnicityData = (Map<String, Integer>) request.getAttribute("ethnicityBreakdown");

      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    var labels = [];\n");
      out.write("    var values = [];\n");
      out.write("    ");

        for (Map.Entry<String, Integer> entry : ageData.entrySet()) {
    
      out.write("\n");
      out.write("        labels.push(\"");
      out.print( entry.getKey() );
      out.write("\");\n");
      out.write("        values.push(");
      out.print( entry.getValue() );
      out.write(");\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("\n");
      out.write("    new Chart(document.getElementById(\"ageChart\"), {\n");
      out.write("        type: \"bar\",\n");
      out.write("        data: {\n");
      out.write("            labels: labels,\n");
      out.write("            datasets: [{\n");
      out.write("                label: \"Number of Patients\",\n");
      out.write("                data: values,\n");
      out.write("                backgroundColor: \"rgba(54, 162, 235, 0.5)\",\n");
      out.write("                borderColor: \"rgba(54, 162, 235, 1)\",\n");
      out.write("                borderWidth: 1\n");
      out.write("            }]\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    labels = [];\n");
      out.write("    values = [];\n");
      out.write("\n");
      out.write("    ");

        for (Map.Entry<String, Integer> entry : ethnicityData.entrySet()) {
    
      out.write("\n");
      out.write("        labels.push(\"");
      out.print( entry.getKey() );
      out.write("\");\n");
      out.write("        values.push(");
      out.print( entry.getValue() );
      out.write(");\n");
      out.write("    ");

        }
    
      out.write("\n");
      out.write("\n");
      out.write("    new Chart(document.getElementById(\"ethnicityChart\"), {\n");
      out.write("        type: \"bar\",\n");
      out.write("        data: {\n");
      out.write("            labels: labels,\n");
      out.write("            datasets: [{\n");
      out.write("                label: \"Number of Patients\",\n");
      out.write("                data: values,\n");
      out.write("                backgroundColor: \"rgba(249, 115, 22, 0.5)\",\n");
      out.write("                borderColor: \"rgba(249, 115, 22, 1)\",\n");
      out.write("                borderWidth: 1\n");
      out.write("            }]\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    new Chart(document.getElementById(\"aliveDeadChart\"), {\n");
      out.write("        type: \"pie\",\n");
      out.write("        data: {\n");
      out.write("            labels: [\"Alive\", \"Dead\"],\n");
      out.write("            datasets: [{\n");
      out.write("                data: [");
      out.print( alive );
      out.write(',');
      out.write(' ');
      out.print( dead );
      out.write("],\n");
      out.write("                backgroundColor: [\n");
      out.write("                     \"rgba(34, 197, 94, 0.5)\",\n");
      out.write("                     \"rgba(239, 68, 68, 0.5)\"\n");
      out.write("                ],\n");
      out.write("                borderColor: [\n");
      out.write("                    \"rgba(34, 197, 94, 1)\",\n");
      out.write("                    \"rgba(239, 68, 68, 1)\"\n");
      out.write("                ],\n");
      out.write("                borderWidth: 1\n");
      out.write("            }]\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    new Chart(document.getElementById(\"maleFemaleChart\"), {\n");
      out.write("        type: \"pie\",\n");
      out.write("        data: {\n");
      out.write("            labels: [\"Male\", \"Female\"],\n");
      out.write("            datasets: [{\n");
      out.write("                data: [");
      out.print( male );
      out.write(',');
      out.write(' ');
      out.print( female );
      out.write("],\n");
      out.write("                backgroundColor: [\n");
      out.write("                    \"rgba(75, 192, 192, 0.5)\",\n");
      out.write("                    \"rgba(255, 99, 132, 0.5)\"\n");
      out.write("                ],\n");
      out.write("                borderColor: [\n");
      out.write("                    \"rgba(75, 192, 192, 1)\",\n");
      out.write("                    \"rgba(255, 99, 132, 1)\"\n");
      out.write("                ],\n");
      out.write("                borderWidth: 1\n");
      out.write("            }]\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    new Chart(document.getElementById(\"marriedSingleChart\"), {\n");
      out.write("        type: \"pie\",\n");
      out.write("        data: {\n");
      out.write("            labels: [\"Married\", \"Single\", \"Unknown\"],\n");
      out.write("            datasets: [{\n");
      out.write("                data: [");
      out.print( married );
      out.write(',');
      out.write(' ');
      out.print( single );
      out.write(',');
      out.write(' ');
      out.print( unknown);
      out.write("],\n");
      out.write("                backgroundColor: [\n");
      out.write("                    \"rgba(168, 85, 247, 0.5)\",   \n");
      out.write("                    \"rgba(234, 179, 8, 0.5)\",  \n");
      out.write("                    \"rgba(148, 163, 184, 0.5)\"   \n");
      out.write("                ],\n");
      out.write("                borderColor: [\n");
      out.write("                    \"rgba(168, 85, 247, 1)\",\n");
      out.write("                    \"rgba(234, 179, 8, 1)\",\n");
      out.write("                    \"rgba(148, 163, 184, 1)\"\n");
      out.write("                ],\n");
      out.write("                borderWidth: 1\n");
      out.write("            }]\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    \n");
      out.write("</script>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
